### ISSUE TITLE
add more fields similar to nationatlity / currency

### ISSUE THREAD

**Issue by shadiakiki1986** [teamshadi/mf-dataentry#7]
- subtype, subcategory, etc.

**Comment by minerva22** [comment]
@shadiakiki1986 you can merge the branch export with the origin, I did the necessary tests.

**Comment by shadiakiki1986** [comment]
@minerva22 Great, thanks! Just don't close the issue next time. We'll close it *after* we merge with the *master* branch

**Comment by shadiakiki1986** [comment]
closing this in favor of #4
