### ISSUE TITLE
add tests in save_export branch

### ISSUE THREAD

**Issue by shadiakiki1986** [teamshadi/mf-dataentry#8]
Use [blotter tests](https://github.com/teamshadi/ffa-blotter/tree/master/zipline_app/tests/zipline_app) as reference

Let's start with tests for

- [x] name displayed of a category has "(LB, AE)" suffix if "code_leb" and "code_dub" are not None
- [x] save of a security bond should raise an exception if "code_leb" or "cod_dub" are missing

**Comment by minerva22** [comment]
@shadiakiki1986 I pushed the test unit for :"save of a security bond should raise an exception if "code_leb" or "cod_dub" are missing"

**Comment by shadiakiki1986** [comment]
I can't see any commits related to the tests. Did you push your commits?

**Comment by minerva22** [comment]
sorry I thought that I pushed my commits.
But I have received the error below:

remote: Permission to teamshadi/mf-dataentry.git denied to minerva22.

**Comment by shadiakiki1986** [comment]
I just gave you access. Can you try again?

**Comment by minerva22** [comment]
still [permission denied
